version: "2"

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - migrations

output:
  format: colored-line-number

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - errcheck
      text: "defer .*Close.*"
    - linters:
        - revive
      text: "should have comment or be unexported"
    - linters:
        - unused
      text: "parameter '.*' seems to be unused"
    - linters:
        - forbidigo
      path: ".*_test.go"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gocritic
    - ineffassign
    - unused
    - nakedret
    - bodyclose
    - forbidigo

linters-settings:
  goimports:
    local-prefixes: github.com/nomenarkt/vitaltrack

  forbidigo:
    forbid:
      - name: "fmt.Println"
        message: "Use structured logger instead (zap, slog, etc.)"
      - name: "log.Println"
        message: "Avoid standard log, use centralized logger"
      - name: "log.Fatal"
        message: "Do not call log.Fatal directly in app — use graceful shutdown"
    path-exclude:
      - "**/*_test.go"
      - "**/testdata/**"
    exclude-files:
      - internal/di/**/*.go
      - internal/server/**/*.go
