version: "2"

run:
  timeout: 3m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gocritic
    - ineffassign
    - unused
    - nakedret
    - bodyclose
    - forbidigo
