run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - migrations

output:
  format: colored-line-number

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - errcheck
      text: "defer .*Close.*"
    - linters:
        - revive
      text: "should have comment or be unexported"
    - linters:
        - unused
      text: "parameter '.*' seems to be unused"
    - linters:
        - depguard
      path: ".*_test.go"
      text: "Do not import internal layers directly. Use DI layer."
    - linters:
        - forbidigo
      path: ".*_test.go"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - revive
    - gocritic
    - ineffassign
    - unused
    - typecheck
    - depguard
    - nakedret
    - bodyclose
    - forbidigo
    - copyloopvar

linters-settings:
  goimports:
    local-prefixes: github.com/nomenarkt/vitaltrack

  depguard:
    list-type: blacklist
    packages:
      - github.com/nomenarkt/vitaltrack/backend/internal/domain
      - github.com/nomenarkt/vitaltrack/backend/internal/usecase
      - github.com/nomenarkt/vitaltrack/backend/internal/infra
      - github.com/nomenarkt/vitaltrack/backend/internal/logic
      - github.com/nomenarkt/vitaltrack/backend/internal/server
    short-message: "Do not import internal layers directly. Use DI layer."
    exclude:
      - github.com/nomenarkt/vitaltrack/backend/internal/**


    forbidigo:
      forbid:
        - name: "fmt.Println"
          message: "Use structured logger instead (zap, slog, etc.)"
        - name: "log.Println"
          message: "Avoid standard log, use centralized logger"
        - name: "log.Fatal"
          message: "Do not call log.Fatal directly in app — use graceful shutdown"
      path-exclude:
        - "**/*_test.go"
        - "**/testdata/**"
      exclude-files:
        - internal/di/**/*.go
        - internal/server/**/*.go

